# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: St John's Go Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Download Tailwind CSS Standalone CLI
      run: |
        curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
        chmod +x tailwindcss-linux-x64
        mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

    - name: Run Tailwind CLI to compile CSS
      run: tailwindcss -i ./web/static/styles/tailwind-input.css -o ./web/static/styles/tailwind-output.css --minify

    - name: Generate templates using templ
      run: |
        go install github.com/a-h/templ/cmd/templ@latest
        templ generate
      
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/main.go
      
    # - name: Test with the Go CLI
    #   run: go test

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/stjohns-go-web-app:latest
        build-args: |
          COMMIT_SHA=${{ github.sha }}
          BRANCH=${{ github.ref }}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          VERSION=1.0.0
        file: ./Dockerfile
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        key: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}
        port: ${{ secrets.DIGITAL_OCEAN_PORT }}
        script: |
          docker stop stjohns-go-web-app
          docker rm stjohns-go-web-app
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/stjohns-go-web-app:latest
          docker run -d --name stjohns-go-web-app -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/stjohns-go-web-app:latest
